// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUBi5BHlBJ26cxKZqN24aM716R013OQW4',
    appId: '1:360365515904:web:90cd5e6bb92c1f25947265',
    messagingSenderId: '360365515904',
    projectId: 'k9-app-38850',
    authDomain: 'k9-app-38850.firebaseapp.com',
    storageBucket: 'k9-app-38850.appspot.com',
    measurementId: 'G-H0291K78H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPmBvCUJvZcKCf2aVMmMYHMnHmJ7U2wJA',
    appId: '1:360365515904:android:a7785ea41bb1031b947265',
    messagingSenderId: '360365515904',
    projectId: 'k9-app-38850',
    storageBucket: 'k9-app-38850.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoRU4VYS8IPauajvzH5_k1UgLn4s5ns0Q',
    appId: '1:360365515904:ios:014919134cc56f9d947265',
    messagingSenderId: '360365515904',
    projectId: 'k9-app-38850',
    storageBucket: 'k9-app-38850.appspot.com',
    androidClientId: '360365515904-9vhu2qc3fpntmupaando8fuqbpe4asp1.apps.googleusercontent.com',
    iosClientId: '360365515904-ekr74pi0r97iinlqptr56u1sekho3u7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoRU4VYS8IPauajvzH5_k1UgLn4s5ns0Q',
    appId: '1:360365515904:ios:014919134cc56f9d947265',
    messagingSenderId: '360365515904',
    projectId: 'k9-app-38850',
    storageBucket: 'k9-app-38850.appspot.com',
    androidClientId: '360365515904-9vhu2qc3fpntmupaando8fuqbpe4asp1.apps.googleusercontent.com',
    iosClientId: '360365515904-ekr74pi0r97iinlqptr56u1sekho3u7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUBi5BHlBJ26cxKZqN24aM716R013OQW4',
    appId: '1:360365515904:web:c54862eb72833d47947265',
    messagingSenderId: '360365515904',
    projectId: 'k9-app-38850',
    authDomain: 'k9-app-38850.firebaseapp.com',
    storageBucket: 'k9-app-38850.appspot.com',
    measurementId: 'G-ELZ71YMGSB',
  );

}